### ISSUE TITLE
How to change state manually?

### ISSUE THREAD

**Issue by FaridLU** [shrikanth7698/Custom-Navigation-Drawer#3]
suppose I want to open Messages feed when I open my app with Massages state as selected. How can I do that?

**Comment by YogevUzan** [comment]
I'm having the same issue right now, any progress??

**Comment by FaridBD** [comment]
no :/

**Comment by shrikanth7698** [comment]
guys I'm working on that. give me some time ill draft a new release.

**Comment by wykeenjenga** [comment]
> suppose I want to open Messages feed when I open my app with Massages state as selected. How can I do that?

you can add your own activity to handle that
